// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvDvrT7oN1KCrgC-g5hvGPpmQ72Oaxlb4',
    appId: '1:849209827409:web:6268e991ddb88143c81870',
    messagingSenderId: '849209827409',
    projectId: 'lyra-guardian-app',
    authDomain: 'lyra-guardian-app.firebaseapp.com',
    databaseURL: 'https://lyra-guardian-app-default-rtdb.firebaseio.com',
    storageBucket: 'lyra-guardian-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWIF3Os6RZLuVsZcggbKLzqf00iRR24Zc',
    appId: '1:849209827409:android:c6d094be8eea9b9cc81870',
    messagingSenderId: '849209827409',
    projectId: 'lyra-guardian-app',
    databaseURL: 'https://lyra-guardian-app-default-rtdb.firebaseio.com',
    storageBucket: 'lyra-guardian-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1Vfe7sMGJRP7qLJzRjVlrSGDPcB9MNc',
    appId: '1:849209827409:ios:52a9ff85a36b95cac81870',
    messagingSenderId: '849209827409',
    projectId: 'lyra-guardian-app',
    databaseURL: 'https://lyra-guardian-app-default-rtdb.firebaseio.com',
    storageBucket: 'lyra-guardian-app.firebasestorage.app',
    iosBundleId: 'com.example.lyraNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ1Vfe7sMGJRP7qLJzRjVlrSGDPcB9MNc',
    appId: '1:849209827409:ios:7738976866b22786c81870',
    messagingSenderId: '849209827409',
    projectId: 'lyra-guardian-app',
    storageBucket: 'lyra-guardian-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvDvrT7oN1KCrgC-g5hvGPpmQ72Oaxlb4',
    appId: '1:849209827409:web:9f011cc009da4816c81870',
    messagingSenderId: '849209827409',
    projectId: 'lyra-guardian-app',
    authDomain: 'lyra-guardian-app.firebaseapp.com',
    databaseURL: 'https://lyra-guardian-app-default-rtdb.firebaseio.com',
    storageBucket: 'lyra-guardian-app.firebasestorage.app',
  );

}